spring:
  application:
    name: Spring-boot-mysql-docker-compose
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    url:  ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server.port: 9090